In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import ast

In [2]:
path = 'C:/Users/82109/Desktop'

In [4]:
베스트셀러 = pd.read_excel(path + '/데이터 전처리/책소개 키워드 추출.xlsx')

In [33]:
best = 베스트셀러.iloc[:, 1:]
best

상품명  \
0                            위기의 역사   
1                돈의 속성(300쇄 리커버에디션)   
2                            부자의 그릇   
3                             사장학개론   
4                         EBS 다큐프라임   
...                             ...   
3720                         독서의 역사   
3721                             표준   
3722          삼국지연의보다 재미있는 정사 삼국지 1   
3723  나도 손글씨 바르게 쓰면 소원이 없겠네(핸디 워크북)   
3724                         성격의 탄생   

                                                    책소개  \
0     40만 독자가 선택한 오건영의 글로벌 경제사 특강\n누적 조회 수 550만 회 달성...   
1     2020ㆍ2021ㆍ2022ㆍ2023 4년 연속 최장기 베스트셀러\n80만 깨어있는 ...   
2     수많은 젊은 부자가 꼽은 최고의 ‘부자학 입문서’ 『부자의 그릇』 양장 개정판\n“...   
3     이 책은 과거와 현재,\n미래의 모든 사장을 위한 실무 지침서다\n이 책은 한국과 ...   
4     우리가 반드시 알아야 할 자본주의의 진실!\n『자본주의』는 자본주의를 쉽게 풀어낸 ...   
...                                                 ...   
3720  “독서를 다룬 책 중 가장 빼어난 이야기”\n언어의 파수꾼이자 책의 수호자, 세계 ...   
3721  제4판 표준 중세 국어 문법론에서는 지난 10년 동안에 나온 중세어 관련 문법 업적...   
3722  20만 구독자가 열광한 화제의 유튜브 역사채널 〈써에이스쇼〉의 삼국지\n누적 조회 ...   
3723  아무때나 시간 날 때 틈틈이\n지하철ㆍ학교ㆍ회사ㆍ카페ㆍ집 어느 장소에서도\n편하게 ...   
3724  내 성격은 어떻게 만들어진 걸까?\n왜 사람마다 성격이 다를까?\n성격을 바꿀 수 ...   

                                                    키워드  \
0     ['금리', '모기지', '흥국', '저금리', '글로벌 금융 위기', '실리콘밸리...   
1     ['부자되는법', '종잣돈', '회장', '투자 원칙', '경제철학', '주식 시장...   
2     ['부자되는법', '신용', '소설 형식', '배트', '경제이야기', '사업 아이...   
3         ['창업', '매출', '직원', '장학', '기업인', '사업', '경제경영']   
4     ['재테크', '경제학', '중앙은행', '케인스', '경제이론', '국부론', '...   
...                                                 ...   
3720  ['독서가', '움베르토 에코', '분서갱유', '지배 세력', '성서', '진시황...   
3721    ['품사론', '형태론', '통사론', '표기법', '겹문장', '발음', '인문']   
3722  ['판타지', '황건적', '유비', '컬러 삽화', '위촉', '실제 역사', '...   
3723     ['악필', '교정', '원고지', '정자체', '스프링', '지하철', '인문']   
3724     ['과학', '외향성', '유전학', '친화성', '규명', '개인차', '인문']   

                                                책소개 키워드  
0     {'경제', '글로벌', '오건', '화제', '강의', '금융위기', '외환위기'...  
1     {'경제', '연속', '개국', '메시지', '도서', '증보', '회장', '필...  
2     {'대표', '경제', '가르침', '소개', '다른', '의장', '불어', '하...  
3     {'규모', '학교', '경우', '도서', '가지', '중간', '속성', '선배...  
4     {'자본주의', '지식', '다큐프라임', '모든', '출금', '부작', '시스템...  
...                                                 ...  
3720  {'지성', '은밀', '의미', '성서', '가라', '진시황제', '알베르토',...  
3721  {'자료', '기능', '구성', '요소', '문법', '의미', '지난', '기법...  
3722  {'각인', '과장', '의미', '멸망', '머릿속', '콘텐츠', '문체', '...  
3723  {'학교', '악필', '틈틈이', '스프링', '글귀', '여러', '핵심', '...  
3724  {'장단점', '특성', '내재', '라이프', '소개', '다른', '화성', '...  

[3725 rows x 4 columns]

In [34]:
best = best.drop_duplicates(keep='last',ignore_index=True)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
count_vect_keyword = CountVectorizer()
book_mat_keyword = count_vect_keyword.fit_transform(best['키워드'])                             

In [63]:
book_mat_keyword.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [64]:
count_vect_keyword.vocabulary_

{'금리': 953,
 '모기지': 2333,
 '흥국': 8775,
 '저금리': 6288,
 '글로벌': 941,
 '금융': 962,
 '위기': 5531,
 '실리콘밸리': 4473,
 '경제경영': 381,
 '부자되는법': 3144,
 '종잣돈': 6620,
 '회장': 8713,
 '투자': 7692,
 '원칙': 5504,
 '경제철학': 391,
 '주식': 6658,
 '시장': 4360,
 '신용': 4439,
 '소설': 3953,
 '형식': 8551,
 '배트': 2828,
 '경제이야기': 388,
 '사업': 3438,
 '아이템': 4637,
 '창업': 7004,
 '매출': 2213,
 '직원': 6871,
 '장학': 6236,
 '기업인': 1034,
 '재테크': 6277,
 '경제학': 392,
 '중앙은행': 6751,
 '케인스': 7418,
 '경제이론': 387,
 '국부론': 803,
 '프레임워크': 8067,
 '잠재': 6192,
 '고객': 431,
 '구루': 749,
 '트래픽': 7717,
 '전술': 6363,
 '프레젠테이션': 8068,
 '투자자': 7704,
 '테슬라': 7601,
 '리튬': 2046,
 '여의도': 5010,
 '니켈': 1382,
 '인플레이션': 5972,
 '정치': 6488,
 '한국': 8270,
 '경제': 380,
 '거시': 241,
 '이코': 5848,
 '복지': 3073,
 '정책': 6484,
 '출간': 7246,
 '당시': 1499,
 '지식': 6822,
 '자본주의': 6100,
 '백만장자': 2837,
 '망상': 2183,
 '정비례': 6452,
 '억만장자': 4881,
 '기본': 1001,
 '법칙': 2918,
 '개인': 211,
 '주가': 6634,
 '하락': 8205,
 '급등': 971,
 '전기차': 6337,
 '공시': 576,
 '주식투자': 6662,
 '성장주': 3829,
 '종목': 6611,
 '

In [66]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim_keyword = cosine_similarity(book_mat_keyword, book_mat_keyword)
print(cosine_sim_keyword.shape)
print(cosine_sim_keyword[:10])

(3723, 3723)
[[1.         0.11111111 0.11111111 ... 0.         0.         0.        ]
 [0.11111111 1.         0.22222222 ... 0.         0.         0.        ]
 [0.11111111 0.22222222 1.         ... 0.         0.         0.        ]
 ...
 [0.20100756 0.10050378 0.10050378 ... 0.         0.         0.        ]
 [0.21081851 0.31622777 0.21081851 ... 0.         0.         0.        ]
 [0.11785113 0.11785113 0.11785113 ... 0.         0.         0.        ]]


In [67]:
cosine_sim_keyword_sroted_index = cosine_sim_keyword.argsort()[:,::-1]
print(cosine_sim_keyword_sroted_index[:5])

[[   0  845  244 ... 2472 2471 1861]
 [   1  399   27 ... 2469 2468 1861]
 [   2  274  631 ... 1344 1345 3722]
 [   3  698  495 ... 2473 2472 1861]
 [   4  342  825 ... 2471 2470 1861]]


In [68]:
title = '브랜드 설계자'

In [56]:
book_title = best[best['상품명']==title]
book_index = book_title.index.values
similar_indexs = cosine_sim_sroted_index[book_index, :10]
print(similar_indexs)

[[  3 698 495 610 254 407 512 631 935 454]]


In [70]:
def find_sim_book_keyword(best, sorted_index, title, top_n):
    book_title = best[best['상품명']==title]
    book_index = book_title.index.values
    similar_indexs = sorted_index[book_index, :top_n]
    print(similar_indexs)
    return best.iloc[similar_indexs[0], :]

In [71]:
find_sim_book_keyword(best, cosine_sim_keyword_sroted_index, title, 10)

[[  5 647 214 669 467 153  46  45  14  79]]


상품명  \
5                            브랜드 설계자   
647                   데이터로 경험을 디자인하라   
214                       비즈니스 스테로이드   
669              게으르지만 콘텐츠로 돈은 잘 법니다   
467  100명의 1인 기업가를 만든 SNS 퍼스널 브랜딩 비법   
153                        프로세스 이코노미   
46             무조건 팔리는 심리 마케팅 기술 100   
45                     뇌, 욕망의 비밀을 풀다   
14                           마케팅 설계자   
79                       브랜드로 남는다는 것   

                                                   책소개  \
5    2023년 상반기 종합 베스트셀러 『마케팅 설계자』의 후속작!\n권정훈(장사 권프로...   
647  《데이터로 경험을 디자인하라》는 디지털 세계에서 어떻게 고객의 마음을 읽고, 어떻게...   
214  먼저 팔고 런칭하라\n출시 전 ‘이것’으로 매출의 90%가 결정된다!\n\n온라인 ...   
669  덜 쓰고, 더 자유롭게 더 벌기 원하는 이들을 위한 맞춤형 콘텐츠로 돈 잘 버는 법...   
467  세상에 나를 어떻게 알릴까? 막막했던\n100명의 1인기업가를 브랜드로 만든\n공감...   
153  BTS, 넷플릭스, 샤오미, 파타고니아…\n팔리는 프로세스는 어떻게 만들어지는가?\...   
46   “잘 파는 사람은 사람의 심리를 알고 있다!”\n고객을 설득하기 전에, 관심부터 끌...   
45   인간의 뇌 속에 숨겨진 구매욕망에 답이 있다!\n많은 기업이 빅데이터를 활용해 마케...   
14   미국 마케팅 업계의 새로운 구루\n자동 수익을 완결한 퍼널 해커\n러셀 브런슨이 온...   
79   《모든 비즈니스는 브랜딩이다》에 이은 실전형 브랜딩 바이블!\n경영을 잘하려면 반드...   

                                                   키워드  \
5    ['프레임워크', '잠재 고객', '구루', '트래픽', '전술', '프레젠테이션'...   
647  ['프레임워크', '인사이트', '잠재 고객', '니즈', '디자인씽킹', '설계'...   
214   ['잠재 고객', '창업', '빌드', '가맹점', '호감', '출시', '경제경영']   
669  ['잠재 고객', '벌기', '창업', '광고비', '해킹', '세일즈', '경제경영']   
467  ['브랜드', '잠재 고객', '수익', '매출', '온라인', '고가', '경제경영']   
153  ['마케팅', '잠재 고객', '프로세스', '이코노미', '과정', '아웃풋', ...   
46   ['잠재 고객', '매출', '심리학', '비즈니스', '설득', '즉시', '경제...   
45   ['매출', '잠재 고객', '소비자행동', '매니지먼트', '뇌연구', '소비자'...   
14   ['잠재 고객', '방문자', '후크', '사다리', '세일즈', '판매', '경제...   
79   ['창업', '잠재 고객', '스타트업', '페르소나', '소비재', '타깃', '...   

                                               책소개 키워드  
5    {'규모', '수익', '극찬', '루트', '도서', '상승', '가지', '셀링...  
647  {'사랑', '디자인', '프로젝트', '디지털', '맥락', '기존', '소개',...  
214  {'점점', '비법', '비용', '목표', '먼저', '마케팅', '기법', '첫...  
669  {'자동', '육아', '성공', '위해', '구성', '중인', '바로', '세상...  
467  {'비법', '경제', '수익', '브랜드', '실질', '지난', '미션', '희...  
153  {'글로벌', '경우', '물건', '마주', '오류', '얼마나', '경쟁력', ...  
46   {'심리', '눈치', '가게', '먼저', '마케팅', '사기', '이상', '라...  
45   {'목표', '바꿈', '모형', '자문', '실용', '우유', '욕망', '상승...  
14   {'규모', '수익', '측정', '상승', '가지', '매력', '구루', '온라...  
79   {'다운', '주력', '위해', '성공', '개인', '실용', '다른', '마케...

In [ ]:
cosine_sim_keyword = cosine_similarity(book_mat_keyword, book_mat_keyword)
print(cosine_sim_keyword.shape)
print(cosine_sim_keyword[:10])

cosine_sim_keyword_sroted_index = cosine_sim_keyword.argsort()[:,::-1]
print(cosine_sim_keyword_sroted_index[:5])

title = '브랜드 설계자'

book_title = best[best['상품명']==title]
book_index = book_title.index.values
similar_indexs = cosine_sim_sroted_index[book_index, :10]
print(similar_indexs)

def find_sim_book_keyword(best, sorted_index, title, top_n):
    book_title = best[best['상품명']==title]
    book_index = book_title.index.values
    similar_indexs = sorted_index[book_index, :top_n]
    print(similar_indexs)
    return best.iloc[similar_indexs[0], :]


find_sim_book_keyword(best, cosine_sim_keyword_sroted_index, title, 10)